changelog:
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change
    - title: 🚀 Features
      labels:
        - feature
    - title: 📖 Docs
      labels:
        - documentation
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - fix
    - title: 👨🏻‍🔬 Unstable
      labels:
        - unstable
    - title: 🧪 Tests
      labels:
        - tests
    - title: Other Changes
      labels:
        - "*"
