#pragma once

// Generated by React Native codegen from `src/specs/NativeAudioWorkletsModule.ts`
// (codegenConfig name: "rnaudioworklets").
#include <rnaudioworkletsJSI.h>

#include <jsi/jsi.h>
#include <memory>

namespace facebook::react {

class NativeAudioWorkletsModule
    : public NativeAudioWorkletsModuleCxxSpec<NativeAudioWorkletsModule> {
 public:
  explicit NativeAudioWorkletsModule(std::shared_ptr<CallInvoker> jsInvoker);

  bool install(jsi::Runtime &runtime);

 private:
  std::shared_ptr<CallInvoker> jsInvoker_;
};

} // namespace facebook::react
