name: CI
on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  format-check:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Format check
      run: yarn format:check

  lint-audio-api:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Lint and typecheck (react-native-audio-api)
      run: |
        yarn workspace react-native-audio-api run lint
        yarn workspace react-native-audio-api run typecheck

  lint-worklets:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Lint and typecheck (react-native-audio-worklets)
      run: |
        yarn workspace react-native-audio-api build
        yarn workspace react-native-audio-worklets run lint
        yarn workspace react-native-audio-worklets run typecheck

  check-audio-enum-sync:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Check enum sync
      run: yarn check-audio-enum-sync

  build-audio-api:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Build (react-native-audio-api)
      run: yarn workspace react-native-audio-api build

  build-worklets:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Build (react-native-audio-worklets)
      run: yarn workspace react-native-audio-worklets build
