ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Uncomment when building for macOS with Catalyst
# ENV['RCT_BUILD_FROM_SOURCE'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Relative path from ios/ to the hoisted react-native package. Must stay relative:
# react_native_post_install joins it as File.join("${PODS_ROOT}", "..", path), and an
# absolute path there produces a broken REACT_NATIVE_PATH in the Pods project.
RN_RELATIVE_PATH = '../../../node_modules/react-native'

target 'FabricExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => true
  )
end

# Minimal XCTest host: links RNAudioAPI + React Native core only
target 'FabricExampleTestHost' do
  pod 'RNAudioAPI', :path => '../../../node_modules/react-native-audio-api'

  use_react_native!(
    :path => RN_RELATIVE_PATH,
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => false
  )

  target 'FabricExampleTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    RN_RELATIVE_PATH,
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
end
